#REGRA DO ( OR ) SO SERA VERDADEIRA SE UMA FOR VERDADEIRA
#REGRA DA EXPRESSÃO ( AND ) SO SERA VERDADEIRA QUANDO AS DUAS FOREM VERDADEIRAS
n1=int(input("DIGITE UM NUMERO: "))
n2=int(input("DIGITE UM NUMERO: "))
sub=n1-n2
print(sub)